#------------------------
# Global Settings

title: Business
description: Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression.
email: devsalah101@gmail.com

#------------------------
# About Us Section

About:
- {title: About, content: On sait depuis longtemps que travailler avec du texte lisible et contenant du sens est source de distractions et empêche de se concentrer sur la mise en page elle-même. L'avantage du Lorem Ipsum sur un texte générique comme 'Du texte.}

#------------------------
# Team Us Section

sectionTitle: Our Team

Team:
- {Face: assets/img/person01.jpg, Name: John Doe, Job: Founder & CEO}
- {Face: assets/img/person02.jpg, Name: Salah Belouad, Job: Web Designer}
- {Face: assets/img/person03.jpg, Name: Math Gage, Job: Photographic}

#------------------------
# Contact Us Section

Contact:
- {title: Contact Us, content: On sait depuis longtemps que travailler avec du texte lisible et contenant du sens est source de distractions et empêche de se concentrer sur la mise en page elle-même. L'avantage du Lorem Ipsum sur un texte générique comme 'Du texte.}
